version: '3.9'
services:
  sistema_concrete_java:
    container_name: sistema_concrete_java_container
    image: didox/validador-cpf-java-turma-devops
    ports: 
      - "3001:8080"
  sistema_concrete_csharp:
    container_name: sistema_concrete_csharp_container
    image: didox/validador-cpf-csharp-turma-devops
    ports: 
      - "3002:80"

# $ docker-compose build
# $ docker-compose up
# $ docker-compose up --detach # modo background
# $ docker-compose stop
# $ docker-compose ps
# $ docker exec -it sistema_concrete_csharp_container bash
# $ docker-compose down
